### ISSUE TITLE
Wrong text after run demo script

### ISSUE THREAD

**Issue by remik** [pimoroni/dot3k#10]
If I ran script `sudo python hello_world.py` then I see only "ello World". 
If I ran this manually in console line by line then I see "Hello World".

I have new Pi2 - is my device too fast? :P

**Comment by Gadgetoid** [comment]
Haha, that's a good hypothesis! I've seen this problem too, but only briefly enough to brush it off as part of my brutal testing on Pi 2. I'll have to look into it in more detail.

**Comment by Gadgetoid** [comment]
I've updated ST7036, the LCD driver library, update it with:

    sudo pip install st7036 --ugprade

And see if your problem goes away!

**Comment by remik** [comment]
You have typo in command, should be:
`sudo pip install st7036 --upgrade`

Yes, it is working. Thanks!
