### ISSUE TITLE
dotHAT for non-raspbian distribution

### ISSUE THREAD

**Issue by OkTekk** [pimoroni/dot3k#19]
Actually using Ubuntu-MATE 15.10..
i modified displayotron bash script to 'not' checking distro 

>**--    IS_RASPBIAN=$(cat /etc/*-release | grep "Raspbian")
>++   IS_RASPBIAN=$(cat /etc/*-release | grep "Ubuntu")**

and removed some package not present in repositories

>**--pkgdeplist=( "git" "python-pip" "python-rpi.gpio" "python-smbus" "python-dev" "python3-pip" "python3-rpi.gpio" "python3-dev" ) # list of all the mandatory apt dependencies
>++ pkgdeplist=( "git" "python-pip" "python-rpi.gpio" "python-smbus" "python-dev" "python3-pip" "python3-rpi.gpio" "python3-smbus" "python3-dev" ) # list of all the mandatory apt dependencies**

afterward, tried to do so manually (with help of [this website](http://www.linuxcircle.com/2015/05/03/how-to-install-smbus-i2c-module-for-python-3/) ) and then, launched DOT script.

Result: 
>Exception:
>Traceback (most recent call last):
>  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
>    status = self.run(options, args)
>  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 304, in run
>    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
>  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1235, in prepare_files
>    req_to_install.assert_source_matches_version()
>  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 465, in assert_source_matches_version
>    % (display_path(self.source_dir), version, self))
>  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 71, in display_path
>    if path.startswith(os.getcwd() + os.path.sep):
>UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)

>Storing debug log for failure in /home/lowlow/.pip/pip.log
>Python 2 library install failed!

**Comment by Gadgetoid** [comment]
This appears to be a broken or malfunctioning install of pip, and not related to dot3k. You might have luck trying some of the answers here: http://stackoverflow.com/questions/26473681/pip-install-numpy-throws-an-error-ascii-codec-cant-decode-byte-0xe2
