### ISSUE TITLE
Menu order confuses path

### ISSUE THREAD

**Issue by lucidbeaming** [pimoroni/dot3k#25]
Using menu.add_item to build a configuration menu, with Backlight(backlight) as a test class.

DotHAT on Pi3 using dothat/advanced/menu.py as source file to rewrite.

menu.add_item('Blue Order/Launch', Backlight(backlight))
menu.add_item('Blue Order/Main patch/E-mu Modular/Fat square', Backlight(backlight))
menu.add_item('Blue Order/Main patch/E-mu Modular/Fat Saw', Backlight(backlight))
menu.add_item('Blue Order/Main patch/Steinway/Hall performance', Backlight(backlight))
menu.add_item('Blue Order/Main patch/Steinway/Honky tonk', Backlight(backlight))
menu.add_item('Blue Order/Channel assignments/1', Backlight(backlight))
menu.add_item('Blue Order/Channel assignments/2', Backlight(backlight))
menu.add_item('Blue Order/Channel assignments/3', Backlight(backlight))
menu.add_item('Blue Order/Channel assignments/4', Backlight(backlight))
menu.add_item('Blue Order/Channel assignments/5', Backlight(backlight))
menu.add_item('Blue Order/Channel assignments/6', Backlight(backlight))
menu.add_item('Blue Order/Channel assignments/7', Backlight(backlight))
menu.add_item('Blue Order/Channel assignments/8', Backlight(backlight))
menu.add_item('Blue Order/Channel assignments/9', Backlight(backlight))
menu.add_item('Blue Order/Channel assignments/10', Backlight(backlight))
menu.add_item('Blue Order/Channel assignments/11', Backlight(backlight))
menu.add_item('Blue Order/Channel assignments/12', Backlight(backlight))
menu.add_item('Blue Order/Channel assignments/13', Backlight(backlight))
menu.add_item('Blue Order/Channel assignments/14', Backlight(backlight))
menu.add_item('Blue Order/Channel assignments/15', Backlight(backlight))
menu.add_item('Blue Order/Channel assignments/16', Backlight(backlight))
menu.add_item('Blue Order/Reverb', Backlight(backlight))
menu.add_item('Blue Order/Chorus', Backlight(backlight))
menu.add_item('AmSynth/Launch', Backlight(backlight))
menu.add_item('Pure Data/Launch', Backlight(backlight))
menu.add_item('Effects/Launch', Backlight(backlight))

The root menu shows:
Blue Order
E-mu Modular
Steinway
Channel assignments
AmSynth
Pure Data
Effects

But, E-mu Modular, Steinway, and Channel assignments are supposed to be sub-menu items as defined in the path defined in each menu.add_item. Also, they are missing from their parent item of Blue Order.

Choosing a menu item such as Steinway yields this sequence of sub-menu items...

Steinway>Main patch>Blue Order>Honky tonk

...which is totally out of sequence as defined in menu.add_item.

Am I missing something here? Some weird punctuation treatment of spaces or something?

**Comment by Gadgetoid** [comment]
I picked this up on the forums too, but it should now be fixed by: 76abe35fd6e80cf3ee06d88e2eeaa647f92ccb94
