### ISSUE TITLE
pip install does not install current version

### ISSUE THREAD

**Issue by bablokb** [pimoroni/dot3k#33]
Is there a reason why not to update the version installable with pip install? The pip-version is installed by your installation-script and there is at least one error that  is already fixed in the master branch.

Bernhard

**Comment by RogueM** [comment]
new versions get pushed to the pypi repo when they are deemed safe to replace the previous one. Sometimes that means some delay, either because the development version in the repo does not provide a critical fix, or because more testing is desirable.
