### ISSUE TITLE
Python 3 inputs

### ISSUE THREAD

**Issue by Elliott0184** [pimoroni/dot3k#48]
Hi there I am using the dothat on a RP3 and have encountered some problems. I am creating an Attendance system and as part of that, they have to enter their staff id. What I can't seem to so is get the raspberry pi to do is;
On one line write please enter your staff id here. (i can do this on its own but not with the following)

Then when they use the USB keypad I would like the screen to show what they are typing. Is this possible? If so can someone either link me to some examples or put some in the comments. Many thanks. 
Elliott

**Comment by RogueM** [comment]
in Python 3, if you call the `input()` function you'll end up with a string, which is exactly what you need to pass on to the dot3k... so, something like this should work I think

```python
staffid = input("What's your name? ")
lcd.write(staffid)
```

... I think displaying the user input as he types it would take quite a bit of efforts, but it would be possible I guess. It depends how critical you see that extra feature.
