### ISSUE TITLE
Extended character set ?

### ISSUE THREAD

**Issue by bigmonkeyboy** [pimoroni/dot3k#5]
Is there any documentation on any extended character set ?  For example is there a degrees symbol ? (usually chr(223) )

**Comment by Gadgetoid** [comment]
The datasheet for the display driver is here: http://www.lcd-module.com/eng/pdf/zubehoer/st7036.pdf

See page 22 for the internal character set.

**Comment by bigmonkeyboy** [comment]
Excellent - thanks.
Degree symbol is indeed  223 or 0xDF
